import { Providers } from "./provider";
import { ColorModeScript } from "@chakra-ui/react";
import Layout from "@/Components/Layout/Layout";
import theme from "@/Chakra/theme";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Providers>
          {/* Find fix for the code below */}
          {/* <ColorModeScript initialColorMode={theme.config.initialColorMode} /> */}
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
